"use client";

import type { jsPDF } from "jspdf";
import { Download } from "lucide-react";
import { useState } from "react";

import type { ChatMessage } from "./chat-interface";

interface ExportPdfButtonProps {
  conversationTitle: string;
  projectName: string;
  messages: ChatMessage[];
  pinnedInsights: Array<{ id: string; content: string; createdAt: string }>;
}

function addHeader(doc: jsPDF, title: string, projectName: string, margin: number): number {
  const pageW = doc.internal.pageSize.getWidth();
  doc.setFillColor(79, 70, 229);
  doc.rect(0, 0, pageW, 14, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(255, 255, 255);
  doc.text("Lumin", margin, 9.5);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text("AI-powered data analysis", margin + 18, 9.5);

  let y = 22;
  doc.setTextColor(17, 24, 39);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text(title, margin, y);
  y += 7;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(107, 114, 128);
  const exportDate = new Date().toLocaleDateString(undefined, {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  doc.text(`Project: ${projectName}  ·  Exported ${exportDate}`, margin, y);
  y += 10;

  doc.setDrawColor(229, 231, 235);
  doc.line(margin, y, pageW - margin, y);
  return y + 8;
}

function addPinnedInsights(
  doc: jsPDF,
  insights: Array<{ content: string }>,
  margin: number,
  contentW: number,
  startY: number,
): number {
  let y = startY;
  const pageH = doc.internal.pageSize.getHeight();

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(79, 70, 229);
  doc.text("Pinned Insights", margin, y);
  y += 6;

  for (const insight of insights) {
    const lines = doc.splitTextToSize(`• ${insight.content}`, contentW - 4);
    if (y + lines.length * 5 + 4 > pageH - margin) {
      doc.addPage();
      y = margin;
    }
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(55, 65, 81);
    doc.text(lines, margin + 2, y);
    y += lines.length * 5 + 3;
  }

  y += 4;
  doc.setDrawColor(229, 231, 235);
  doc.line(margin, y, doc.internal.pageSize.getWidth() - margin, y);
  return y + 8;
}

function addMessages(
  doc: jsPDF,
  messages: ChatMessage[],
  margin: number,
  contentW: number,
  startY: number,
): number {
  let y = startY;
  const pageH = doc.internal.pageSize.getHeight();

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(79, 70, 229);
  doc.text("Conversation", margin, y);
  y += 7;

  for (const msg of messages) {
    if (msg.isLoading) {
      continue;
    }
    const isUser = msg.role === "user";
    const label = isUser ? "You" : "Lumin";
    const labelColor: [number, number, number] = isUser ? [17, 24, 39] : [79, 70, 229];
    const textColor: [number, number, number] = isUser ? [55, 65, 81] : [31, 41, 55];
    const lines = doc.splitTextToSize(msg.content, contentW - 6);

    if (y + lines.length * 5 + 14 > pageH - margin) {
      doc.addPage();
      y = margin;
    }

    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(...labelColor);
    doc.text(label, margin, y);
    y += 5;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(...textColor);
    doc.text(lines, margin + 2, y);
    y += lines.length * 5 + 2;

    if (msg.chartSpec) {
      doc.setFont("helvetica", "italic");
      doc.setFontSize(8);
      doc.setTextColor(107, 114, 128);
      doc.text("[Chart available in the app]", margin + 2, y);
      y += 5;
    }
    y += 3;
  }

  return y;
}

function addFooters(doc: jsPDF, margin: number): void {
  const pageH = doc.internal.pageSize.getHeight();
  const pageW = doc.internal.pageSize.getWidth();
  const total = doc.getNumberOfPages();
  for (let i = 1; i <= total; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(156, 163, 175);
    doc.text(`Page ${i} of ${total}`, pageW - margin, pageH - 8, { align: "right" });
    doc.text("Generated by Lumin", margin, pageH - 8);
  }
}

export function ExportPdfButton({
  conversationTitle,
  projectName,
  messages,
  pinnedInsights,
}: ExportPdfButtonProps) {
  const [exporting, setExporting] = useState(false);

  async function handleExport() {
    setExporting(true);
    try {
      const { jsPDF: JsPDF } = await import("jspdf");
      const doc = new JsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

      const margin = 20;
      const contentW = doc.internal.pageSize.getWidth() - margin * 2;

      let y = addHeader(doc, conversationTitle, projectName, margin);

      if (pinnedInsights.length > 0) {
        y = addPinnedInsights(doc, pinnedInsights, margin, contentW, y);
      }

      addMessages(doc, messages, margin, contentW, y);
      addFooters(doc, margin);

      const filename = `${conversationTitle.replace(/[^a-z0-9]/gi, "-").toLowerCase()}.pdf`;
      doc.save(filename);
    } finally {
      setExporting(false);
    }
  }

  return (
    <button
      type="button"
      onClick={() => void handleExport()}
      disabled={exporting}
      className="inline-flex items-center gap-1.5 h-8 px-3 rounded-lg text-xs font-medium transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
      style={{
        border: "1px solid rgba(129, 140, 248, 0.3)",
        backgroundColor: "rgba(129, 140, 248, 0.08)",
        color: "#818cf8",
      }}
    >
      <Download className="h-3.5 w-3.5" />
      {exporting ? "Exporting…" : "Export PDF"}
    </button>
  );
}
