import {
  boolean,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uuid,
} from "drizzle-orm/pg-core";

/**
 * Base timestamp columns for all tables.
 * Usage: ...timestamps
 */
export const timestamps = {
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
};

/**
 * Users table - syncs with Supabase Auth via database trigger.
 *
 * To set up the trigger in Supabase SQL Editor:
 *
 * ```sql
 * -- Function to sync auth.users to public.users
 * CREATE OR REPLACE FUNCTION public.handle_new_user()
 * RETURNS trigger AS $$
 * BEGIN
 *   INSERT INTO public.users (id, email)
 *   VALUES (NEW.id, NEW.email);
 *   RETURN NEW;
 * END;
 * $$ LANGUAGE plpgsql SECURITY DEFINER;
 *
 * -- Trigger on auth.users insert
 * CREATE OR REPLACE TRIGGER on_auth_user_created
 *   AFTER INSERT ON auth.users
 *   FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
 * ```
 */
export const users = pgTable("users", {
  id: uuid("id").primaryKey(), // References auth.users(id)
  email: text("email").notNull(),
  displayName: text("display_name"),
  avatarUrl: text("avatar_url"),
  ...timestamps,
});

/**
 * Projects table - stores project information with ownership.
 */
export const projects = pgTable("projects", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull(),
  slug: text("slug").notNull().unique(),
  description: text("description"),
  isPublic: boolean("is_public").notNull().default(false),
  ownerId: uuid("owner_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  ...timestamps,
});

/**
 * Data sources table - stores uploaded files (CSV, JSON, text) for a project.
 *
 * Setup required in Supabase:
 *   1. Create a Storage bucket called "data-sources" (private)
 *   2. No RLS needed — server-side operations use the service role key.
 */
export const dataSources = pgTable("data_sources", {
  id: uuid("id").primaryKey().defaultRandom(),
  projectId: uuid("project_id")
    .notNull()
    .references(() => projects.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  type: text("type", { enum: ["csv", "json", "text"] }).notNull(),
  storageKey: text("storage_key").notNull(),
  fileSize: integer("file_size"),
  rowCount: integer("row_count"),
  status: text("status", { enum: ["processing", "ready", "error"] })
    .notNull()
    .default("processing"),
  errorMessage: text("error_message"),
  metadata: jsonb("metadata"),
  ...timestamps,
});

/**
 * Conversations — a thread of messages scoped to a project.
 * A user may have many conversations per project (each with a different
 * set of data sources in scope or a different analysis angle).
 */
export const conversations = pgTable("conversations", {
  id: uuid("id").primaryKey().defaultRandom(),
  projectId: uuid("project_id")
    .notNull()
    .references(() => projects.id, { onDelete: "cascade" }),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  title: text("title").notNull(),
  ...timestamps,
});

/**
 * Messages — individual turns within a conversation.
 * role = "user" | "assistant"
 * chartSpec stores an optional Vega-Lite JSON spec when the AI returns a chart.
 */
export const messages = pgTable("messages", {
  id: uuid("id").primaryKey().defaultRandom(),
  conversationId: uuid("conversation_id")
    .notNull()
    .references(() => conversations.id, { onDelete: "cascade" }),
  role: text("role", { enum: ["user", "assistant"] }).notNull(),
  content: text("content").notNull(),
  /** Vega-Lite spec — present when the assistant decides a chart answers better. */
  chartSpec: jsonb("chart_spec"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

/**
 * Parsed row data extracted from uploaded files.
 * Each row holds a JSONB payload:
 *   - CSV/JSON: { "col": "value", ... }
 *   - Text:     { "text": "chunk content" }
 *
 * Rows are used to build AI context when answering questions.
 */
/**
 * Suggested questions generated by AI when a data source becomes ready.
 * Questions are based on the data schema and sample rows.
 */
export const suggestedQuestions = pgTable("suggested_questions", {
  id: uuid("id").primaryKey().defaultRandom(),
  dataSourceId: uuid("data_source_id")
    .notNull()
    .references(() => dataSources.id, { onDelete: "cascade" }),
  /** Array of plain-English question strings */
  questions: jsonb("questions").notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

/**
 * Pinned insights — assistant messages the user has pinned for later reference.
 * Shown in the dedicated Insights panel on the project page.
 */
export const pinnedInsights = pgTable("pinned_insights", {
  id: uuid("id").primaryKey().defaultRandom(),
  projectId: uuid("project_id")
    .notNull()
    .references(() => projects.id, { onDelete: "cascade" }),
  messageId: uuid("message_id")
    .notNull()
    .references(() => messages.id, { onDelete: "cascade" }),
  content: text("content").notNull(),
  /** Vega-Lite spec if the message had a chart */
  chartSpec: jsonb("chart_spec"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

/**
 * Anomaly alerts detected during data ingestion.
 * Surfaced on the project page to call attention to unusual values.
 */
export const anomalyAlerts = pgTable("anomaly_alerts", {
  id: uuid("id").primaryKey().defaultRandom(),
  projectId: uuid("project_id")
    .notNull()
    .references(() => projects.id, { onDelete: "cascade" }),
  dataSourceId: uuid("data_source_id")
    .notNull()
    .references(() => dataSources.id, { onDelete: "cascade" }),
  columnName: text("column_name").notNull(),
  type: text("type", { enum: ["outlier", "missing_values", "constant", "spike"] }).notNull(),
  description: text("description").notNull(),
  severity: text("severity", { enum: ["low", "medium", "high"] }).notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const dataRows = pgTable(
  "data_rows",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    dataSourceId: uuid("data_source_id")
      .notNull()
      .references(() => dataSources.id, { onDelete: "cascade" }),
    rowNumber: integer("row_number").notNull(),
    data: jsonb("data").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [index("data_rows_data_source_id_idx").on(table.dataSourceId)],
);
